/**
 * Spec #138: working delivery targets for a project that has none.
 *
 * Before this, a fresh project had to hand-write three delivery commands
 * before `poiesis init` would even start; a missing `{sha}` token was a
 * hard `INVALID_DELIVERY_CONFIG` failure. That is exactly the friction the
 * Author asked to remove: install should infer or default, never block.
 *
 * These scripts are ordinary project files. init writes them only when the
 * target is absent, never records them in the manifest, and never rewrites
 * them on update - so the first Author edit is the moment Poiesis stops
 * touching them, with no ownership bookkeeping required.
 */

export const DELIVERY_TARGETS = ["preview", "staging", "production"] as const;
export type DeliveryTarget = (typeof DELIVERY_TARGETS)[number];

export const deliveryScriptPath = (target: DeliveryTarget): string =>
  `scripts/poiesis-${target}.mjs`;

/**
 * The generated script body.
 *
 * `preview` is a genuinely tryable artifact: with a reachable remote and an
 * authenticated `gh`, it opens a DRAFT pull request for the candidate, which
 * is the canonical thing an Author can look at. Without `gh` it still produces
 * a concrete local artifact so the target is never a no-op stub.
 *
 * `staging` and `production` record a release identity under
 * `.poiesis/runtime/delivery/`. A real project replaces these with its own
 * deploy; the point is that a fresh install is complete and inspectable
 * rather than unfinished.
 */
const SCRIPT_BODY = `#!/usr/bin/env node
/**
 * Poiesis delivery target: __TARGET__.
 *
 * GENERATED BY \`poiesis init\` on __INSTALLED_AT__ because this project had no
 * __TARGET__ target configured. This is a plain project file: edit it freely.
 * Once you do, Poiesis never touches it again.
 *
 * Contract: called as \`node scripts/poiesis-__TARGET__.mjs <sha> <target>\`.
 * It must print a single JSON object on stdout describing what it produced.
 */
import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const [, , sha, target] = process.argv;
if (!sha || !target) {
  process.stderr.write("usage: poiesis-__TARGET__.mjs <sha> <target>\\n");
  process.exit(64);
}

function git(args) {
  return spawnSync("git", args, { encoding: "utf8" });
}

const rev = git(["rev-parse", "--verify", \`\${sha}^{commit}\`]);
if (rev.status !== 0) {
  process.stderr.write(\`unknown candidate sha: \${sha}\\n\${rev.stderr}\`);
  process.exit(rev.status ?? 1);
}
const tree = git(["rev-parse", \`\${sha}^{tree}\`]);
if (tree.status !== 0) {
  process.stderr.write(\`unable to resolve candidate tree for \${sha}\\n\${tree.stderr}\`);
  process.exit(tree.status ?? 1);
}
const candidateTree = tree.stdout.trim();

// The delivery artifact always exists on disk, so the target is inspectable
// even when the remote-facing step below cannot run.
const artifactRoot = resolve(process.cwd(), ".poiesis/runtime/delivery", target, sha);
mkdirSync(artifactRoot, { recursive: true });

let commitMessage = "";
const subject = git(["log", "-1", "--format=%s", sha]);
if (subject.status === 0) commitMessage = subject.stdout.trim();

__PREVIEW_BODY__

writeFileSync(
  resolve(artifactRoot, "delivery.json"),
  \`\${JSON.stringify(
    {
      target,
      candidateSha: sha,
      candidateTree,
      commitMessage,
      recordedAt: new Date().toISOString(),
      __RESULT_FIELDS__
    },
    null,
    2,
  )}\\n\`,
);

process.stdout.write(\`\${JSON.stringify({
  target,
  candidateSha: sha,
  candidateTree,
  artifact: \`\${artifactRoot}/delivery.json\`,
  __RESULT_FIELDS__
})}\\n\`);
`;

/**
 * The preview-specific step. Kept separate so the three generated targets
 * share one body and one contract.
 */
const PREVIEW_BODY = `
// A draft PR is the one thing an Author can actually open and try, so that
// is what a generated preview attempts. It is strictly best-effort: a
// project without a remote, without \`gh\`, or without an authenticated
// \`gh\` still produces the local artifact above.
let changeRequest = null;
const remote = git(["remote", "get-url", "origin"]);
if (remote.status === 0) {
  const gh = spawnSync("gh", ["auth", "status"], { encoding: "utf8" });
  if (gh.status === 0) {
    const title = \`draft: \${commitMessage || "poiesis preview"}\`.slice(0, 200);
    const pr = spawnSync(
      "gh",
      [
        "pr", "create",
        "--draft",
        "--title", title,
        "--body",
        \`Poiesis preview for \${sha}\\n\\ncandidate tree: \${candidateTree}\\n\\nChange Request: Draft Preview\\n\`,
      ],
      { encoding: "utf8" },
    );
    if (pr.status === 0) {
      const url = (pr.stdout || "").trim().split("\\n").pop() || "";
      changeRequest = { id: url || null, url: url || null, state: "draft" };
    }
  }
}
`;

const RECORD_BODY = `
// A real project replaces this with its own deploy step. The identity is
// recorded so the target is complete, inspectable, and never a silent no-op.
const release = { released: true, recordedAt: new Date().toISOString() };
`;

/** The full generated script for one target. */
export function renderDefaultDeliveryScript(target: DeliveryTarget, installedAt: string): string {
  return SCRIPT_BODY.split("__TARGET__").join(target)
    .split("__INSTALLED_AT__").join(installedAt)
    .split("__PREVIEW_BODY__").join(target === "preview" ? PREVIEW_BODY : RECORD_BODY)
    .split("__RESULT_FIELDS__")
    .join(
      target === "preview"
        ? "changeRequest: changeRequest ?? null,"
        : "release,",
    );
}

/** The delivery adapter the generated script corresponds to. */
export function defaultDeliveryAdapter(target: DeliveryTarget): {
  adapter: "command";
  command: string[];
} {
  return {
    adapter: "command",
    command: ["node", deliveryScriptPath(target), "{sha}", "{target}"],
  };
}
